### ISSUE TITLE
How to load .obj files as meshes

### ISSUE THREAD

**Issue by HeegerGao** [kevinzakka/mujoco_scanned_objects#1]
Hi, I am not sure I undertand the right way to use your models in mujoco. 

I saw that you are using .obj files as meshes in .xml files of each object. I think this is not feasible for mujoco since mujoco does not support .obj files as mesh. Directly dragging the .xml file into simulator will cause an error: `Error: Unknown mesh file type: model.obj`. Is there any explanation about this?

**Comment by kevinzakka** [comment]
Hey @HeegerGao, MuJoCo has had support for OBJ files since version [2.1.2](https://github.com/deepmind/mujoco/releases/tag/2.1.2). What version are you using?

**Comment by HeegerGao** [comment]
> Hey @HeegerGao, MuJoCo has had support for OBJ files since version [2.1.2](https://github.com/deepmind/mujoco/releases/tag/2.1.2). What version are you using?

Oh really? I am using 2.1.0. Let me check 2.1.2. Thank you!

**Comment by HeegerGao** [comment]
> > Hey @HeegerGao, MuJoCo has had support for OBJ files since version [2.1.2](https://github.com/deepmind/mujoco/releases/tag/2.1.2). What version are you using?
> 
> Oh really? I am using 2.1.0. Let me check 2.1.2. Thank you!

Hi, I update my mujoco to 2.2.0 and everything is OK now. Thank you!
